"use client";

import { motion, AnimatePresence } from "framer-motion";
import { 
  Terminal, ShieldCheck, Zap, Power, 
  Search, Plus, Save, Trash2, Edit3,
  Loader2, Sparkles, Send, Bot, RefreshCcw
} from "lucide-react";
import { useState, useEffect } from "react";
import { supabase } from "@/lib/supabase";

export default function TelegramCommandsPage() {
  const [commands, setCommands] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchCommands();
  }, []);

  const fetchCommands = async () => {
    setLoading(true);
    // Shared table dc_commands but with platform='telegram'
    const { data } = await supabase.from("dc_commands").select("*").eq("platform", "telegram").order("name", { ascending: true });
    if (data) setCommands(data);
    setLoading(false);
  };

  return (
    <div className="w-full space-y-6 z-10 lg:pl-4 mb-20">
      <header className="mb-10 flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-blue-500/10 text-blue-600 rounded-xl animate-pulse">
                <Terminal size={20} />
            </div>
            <span className="text-xs font-bold text-blue-500 uppercase tracking-widest">Logic Node Controller</span>
          </div>
          <h1 className="text-4xl font-extrabold text-sunset-900 tracking-tight glow-text-sunset">
            Telegram <span className="text-blue-500/40">Logic Hub</span>
          </h1>
          <p className="text-sunset-800/70 font-medium max-w-xl">
             Define bot commands and automated triggers for your Telegram users. Synchronized with N8N logic.
          </p>
        </div>
        
        <div className="flex gap-3">
             <button className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white font-bold rounded-2xl shadow-xl shadow-blue-500/20 hover:bg-blue-700 transition-all active:scale-95">
                <Plus size={20} /> Deploy Command
            </button>
        </div>
      </header>

      <div className="grid grid-cols-1 xl:grid-cols-12 gap-8 items-start">
        
        {/* Logic Grid */}
        <div className="xl:col-span-8 grid grid-cols-1 md:grid-cols-2 gap-4">
            {loading ? (
                <div className="col-span-full flex justify-center p-20"><Loader2 className="animate-spin text-blue-500" /></div>
            ) : commands.length === 0 ? (
                <div className="col-span-full glass-card p-20 text-center border-dashed border-2 border-blue-200 italic font-bold opacity-30 text-blue-950">
                    Your Telegram logic nodes are offline. Add the first command to initiate.
                </div>
            ) : (
                commands.map((cmd) => (
                    <motion.div 
                        key={cmd.id}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="glass-card p-6 rounded-[2rem] border border-blue-50 shadow-lg group hover:border-blue-200 transition-all"
                    >
                        <div className="flex justify-between items-start mb-6">
                            <div className="flex items-center gap-3">
                                <div className="p-3 bg-blue-50 text-blue-600 rounded-2xl">
                                    <Bot size={20} />
                                </div>
                                <div>
                                    <h4 className="text-lg font-black text-blue-950 italic">/{cmd.name}</h4>
                                    <span className="text-[10px] font-black opacity-30 uppercase tracking-widest leading-none">Command ID: {cmd.id}</span>
                                </div>
                            </div>
                            <button className="p-2 text-blue-500 hover:bg-blue-50 rounded-xl transition-all"><Edit3 size={18} /></button>
                        </div>
                        
                        <p className="text-xs font-medium text-sunset-800/60 mb-6 italic line-clamp-3">
                            "{cmd.response_text || 'Automated response generated by logic hub'}"
                        </p>

                        <div className="flex items-center justify-between border-t border-blue-50 pt-4">
                             <div className="flex items-center gap-2">
                                <ShieldCheck size={14} className="text-emerald-500" />
                                <span className="text-[10px] font-black text-emerald-600 uppercase">ACCESS: PUBLIC</span>
                             </div>
                             <div className="flex items-center">
                                <label className="relative inline-flex items-center cursor-pointer">
                                    <input type="checkbox" className="sr-only peer" checked />
                                    <div className="w-11 h-6 bg-slate-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                                </label>
                            </div>
                        </div>
                    </motion.div>
                ))
            )}
        </div>

        {/* Global Control Terminal */}
        <div className="xl:col-span-4 space-y-6">
            <div className="glass-card p-8 rounded-[2.5rem] bg-indigo-950 text-white shadow-2xl relative overflow-hidden group">
                 <div className="absolute right-0 bottom-0 opacity-10 rotate-12 group-hover:rotate-45 transition-transform duration-1000"><Terminal size={200} /></div>
                 <h3 className="text-xl font-black mb-6 flex items-center gap-3 subrayado-glow">
                    <Sparkles size={24} className="text-yellow-400" /> Sync N8N
                 </h3>
                 <p className="text-white/60 text-xs mb-8 italic font-medium leading-relaxed">
                    Trigger a manual synchronization between the cloud logic nodes and your Telegram bot instance. This will flush the cache.
                 </p>
                 <button className="w-full py-4 bg-indigo-600 text-white font-black text-xs rounded-2xl shadow-xl hover:bg-indigo-500 transition-all uppercase tracking-[0.2rem] flex items-center justify-center gap-2">
                    <RefreshCcw size={16} /> Force Logic Flush
                 </button>
            </div>

            <div className="glass-card p-8 rounded-[2.5rem] border border-blue-100 bg-blue-50/50 backdrop-blur-md">
                <h4 className="font-bold text-blue-900 mb-6 flex items-center gap-2"><Send size={18} /> API Health</h4>
                <div className="space-y-4">
                    <div className="flex justify-between items-center bg-white p-3 rounded-2xl border border-blue-100 italic">
                        <span className="text-[10px] font-black text-blue-950/40">BOT STATUS</span>
                        <span className="text-[10px] font-black text-emerald-600 uppercase">LINKED</span>
                    </div>
                    <div className="flex justify-between items-center bg-white p-3 rounded-2xl border border-blue-100 italic">
                        <span className="text-[10px] font-black text-blue-950/40">LATENCY</span>
                        <span className="text-[10px] font-black text-blue-600">12ms</span>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  );
}
